name: Login Test
on: [create, push]
jobs:
  Login:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [14.x]
    name: Login to Github acount
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }} 
      - name: Install gauge
        run: npm install @getgauge/cli 
      - name: Install Dependencies
        run: npm run start
      - name: Test flow
        run: npm run test
